### PR TITLE
Add `echo_to` option to echo the messages received by the transport to a specified MSISDN

### PR DESCRIPTION
**Pull request by Hannarst**

### CODE REVIEW

**Comment by Hannarst** [comment]
@hodgestar  Should I rather create a variable for `self.transport.config.echo_to`?

**Comment by hodgestar** [comment]
@Hannarst Yep. Agreed that an attribute would be nicer than accessing config directly.

**Comment by Hannarst** [comment]
@hodgestar An attribute of the `WhatsAppInterface` class?

**Comment by hodgestar** [comment]
I was thinking to the transport, but passing it in to
`WhatsAppInterface.__init__` as a parameter is cool too. Pick whatever
looks good to you?

**Comment by Hannarst** [comment]
```python
def __init__(self, transport):
    super(WhatsAppInterface, self).__init__()
    self.transport = transport
    self.echo_to = self.transport.config.echo_to
```
or:
```python
def __init__(self, transport):
    super(WhatsAppInterface, self).__init__()
    self.transport = transport
    self.echo_to = transport.config.echo_to
```
?
Or something else?

**Comment by hodgestar** [comment]
```python
def __init__(self, transport, echo_to=None):
    super(WhatsAppInterface, self).__init__()
    self.transport = transport
    self.echo_to = echo_to
```
Not sure this is objectively better -- just seems nice(r) to me.

**Comment by Hannarst** [comment]
And expand the `__init__` in `StackClient` to this? :confused: 
```python
def __init__(self, credentials, transport, echo_to=None):
    self.CREDENTIALS = credentials
    self.transport = transport
   self.echo_to = echo_to
    # etc.
```

**Comment by hodgestar** [comment]
That would be needed. Agreed that passing `echo_to` around everywhere
quickly becomes annoying. Happy with `self.transport.echo_to` instead if
you prefer?

**Comment by Hannarst** [comment]
@hodgestar Ready for review

**Comment by hodgestar** [comment]
:+1:

**Pull request closed without merging**
