### PR TITLE
Add Anna to the AUTHORS file.

### PR DESCRIPTION
**Pull request by Hannarst**

### CODE REVIEW

**Comment by Hannarst** [comment]
@hodgestar Ready for review I guess :| 
Maybe I've missed some formatting issue or something.

**Comment by hodgestar** [comment]
You should be at the top of the list because it's sorted alphabetically by first name. :)

**Comment by Hannarst** [comment]
@hodgestar woot?

**Comment by hodgestar** [comment]
Woot.

**Comment by hodgestar** [comment]
:+1:

**Pull request merged**
