### PR TITLE
Falsify connection to WhatsApp

### PR DESCRIPTION
**Pull request by Hannarst**
Using a testing layer to replace the Coder Layer and all those below

### CODE REVIEW

**Comment by Hannarst** [comment]
@hodgestar

**Comment by hodgestar** [comment]
@Hannarst You need to add `vxyowsup/tests/__init__.py` (it can be blank) so that trial realises the tests folder is a Python package.

**Comment by Hannarst** [comment]
:+1:

**Comment by hodgestar** [comment]
:+1: on your commits.

**Pull request closed without merging**
